name: "Run PHIVE in GitHub Actions"

on:
  - "push"
  - "pull_request"

jobs:
  phive:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "7.4"
          - "7.3"
    steps:
      - name: "Set default PHP version"
        run: "sudo update-alternatives --set php /usr/bin/php${{ matrix.php-version }}"

      - name: "Determine .phive path"
        id: "determine-phive"
        run: "echo \"::set-output name=home::${HOME}/.phive\""

      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Cache tools installed with PHIVE"
        uses: "actions/cache@v2"
        with:
          #path: "${{ runner.temp }}/.phive"
          path: "${{ steps.determine-phive.outputs.home }}"
          key: "phive-${{ matrix.php-version }}-phar-${{ hashFiles('.phive/phars.xml') }}"
          restore-keys: "phive-${{ matrix.php-version }}-phar-"

      - name: "Install PHIVE"
        uses: "szepeviktor/phive@v1"
        with:
          #home: "${{ runner.temp }}/.phive"
          home: "${{ steps.determine-phive.outputs.home }}"

      - name: "Install PHP tools with PHIVE"
        uses: "szepeviktor/phive-install@v1"
        with:
          #home: "${{ runner.temp }}/.phive"
          home: "${{ steps.determine-phive.outputs.home }}"
          trustGpgKeys: "4AA394086372C20A,CF1A108D0E7AE720,E82B2FB314E9906E"

      - name: "Show what was being installed!"
        run: "find ~ -path '*phive*'"
